language: php
sudo: required
dist: trusty
php: 7.0
script:
 - wget https://github.com/magento/magento2/archive/2.1.5.zip
 - unzip -qq 2.1.5.zip
 - cd magento2-2.1.5/
 - composer require --no-interaction "monashee/recaptcha":"dev-master"
 - ./vendor/bin/phpunit -c vendor/monashee/recaptcha/phpunit.xml.dist